### PR TITLE
Add globally available method to allow for uploading binary object

### PR DESCRIPTION
**Pull request by hjpotter92**
I think instead of having a different method, it can be managed by the same `upload` call.

References #186.

### CODE REVIEW

**Comment by maxtepkeev** [comment]
I don't see why we need additional method for this, just implement this logic inside existing ``upload`` method, also a test should be added to test this

**Comment by hjpotter92** [comment]
@maxtepkeev For tests, I'd have to create a StringIO instance. I am not sure whether that is a good idea though!

**Comment by maxtepkeev** [comment]
@hjpotter92 Sorry for the delay with reply. Can you please elaborate why do you think it may be not a good idea ?

**Comment by hjpotter92** [comment]
It'd require different test cases (or try-catch implementation) for different python versions; which I consider to be a hacky method.

**Comment by hjpotter92** [comment]
@maxtepkeev Can you help me a little with writing the test case? I think I'll have to create an equivalent function to [`test_successful_file_upload`][1]? I could add the mock file data directly in the same function? What would the response be if I pass a file object?

  [1]: https://github.com/maxtepkeev/python-redmine/blob/master/tests/test_redmine.py#L59

**Comment by maxtepkeev** [comment]
@hjpotter92 Thanks again for the PR and sorry for such a delay with an answer, having hard times here... No worries about the test case, I'll write it myself.

**Comment by hjpotter92** [comment]
@maxtepkeev Thanks for merging the PR. :smile: 

BTW, I came across another bug because of this. The `path` keyword argument is being copied over to the final REST call. Since an object is now a valid value for the same, it raises an exception

```pytb
.
.
.
File "/var/task/redminelib/engines/base.py", line 74, in request
kwargs = self.construct_request_kwargs(method, headers, params, data)
File "/var/task/redminelib/engines/base.py", line 57, in construct_request_kwargs
kwargs['data'] = json.dumps(data)
File "/usr/lib64/python2.7/json/__init__.py", line 244, in dumps
return _default_encoder.encode(obj)
File "/usr/lib64/python2.7/json/encoder.py", line 207, in encode
chunks = self.iterencode(o, _one_shot=True)
File "/usr/lib64/python2.7/json/encoder.py", line 270, in iterencode
return _iterencode(o, 0)
File "/usr/lib64/python2.7/json/encoder.py", line 184, in default
raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <StringIO.StringIO instance at 0x7f141da69200> is not JSON serializable
```
For now, as a workaround; I added the following when the data is being jsonified:

```python
            if 'attachments' in data:
                for attachment in data['attachments']:
                    attachment.pop('path')
```

**Comment by maxtepkeev** [comment]
@hjpotter92 Oh I see, ok, thx for letting me know.

**Pull request merged**
