### PR TITLE
Fix UnicodeEncodeError in ResourceManager

### PR DESCRIPTION
**Pull request by kopf**
Iterating over all wiki_pages in my redmine, I got the following error when I tried to re-get the wiki_page (in order to grab all the attachments)

````
2015-01-21 15:42] INFO: redmine2confluence: Importing: Durchführung
Traceback (most recent call last):
  File "redmine2confluence.py", line 37, in <module>
    processed = process(redmine, wiki_page)
  File "redmine2confluence.py", line 15, in process
    wiki_page.title, project_id=project.id, include='attachments')
  File "/Users/awalton/.virtualenvs/redmine/lib/python2.7/site-packages/redmine/managers.py", line 121, in get
    self.url = '{0}{1}'.format(self.redmine.url, self.resource_class.query_one.format(resource_id, **params))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 6: ordinal not in range(128)
````

This pull request should fix this.

### CODE REVIEW

**Comment by maxtepkeev** [comment]
You can't do this because this won't work in Python 3.2 (there is no u'' syntax). Also the problems you're getting is because of u'\xfc' which is the german ü. The strange thing is that I have absolutely no problems here on Python 2.7 with wiki pages having ü in their names. Can you show your exact code which reproduces the error.

**Comment by kopf** [comment]
Hm, funny. Here's the code.

````python
import logbook
from redmine import Redmine

from confluence import Confluence
from convert import wiki_to_confluence
from settings import REDMINE, CONFLUENCE, PROJECTS

log = logbook.Logger('redmine2confluence')


def process(redmine, wiki_page):
    """Processes a wiki page, getting all metadata and reformatting body"""
    # Get again, to get attachments:
    wiki_page = redmine.wiki_page.get(
        wiki_page.title, project_id=project.id, include='attachments')


if __name__ == '__main__':
    redmine = Redmine(REDMINE['url'], key=REDMINE['key'])
    confluence = Confluence(
        CONFLUENCE['url'], CONFLUENCE['username'], CONFLUENCE['password'])
    for proj_name, space in PROJECTS.iteritems():
        log.info(u"Creating space {0}".format(space))
        project = redmine.project.get(proj_name)
        confluence.create_space(space, project.name, project.description)
        for wiki_page in project.wiki_pages:
            log.info(u"Importing: {0}".format(wiki_page.title))
            processed = process(redmine, wiki_page)
````

The error occurs on the line assigning `wiki_page` in `process()`

**Comment by maxtepkeev** [comment]
Thanks for the code.

I was able to reproduce a bug, but this is a sly one, I have to think how to fix it properly.

In the meantime how about using something like this:

```python
import logbook
from redmine import Redmine

from confluence import Confluence
from convert import wiki_to_confluence
from settings import REDMINE, CONFLUENCE, PROJECTS

log = logbook.Logger('redmine2confluence')

if __name__ == '__main__':
    redmine = Redmine(REDMINE['url'], key=REDMINE['key'])
    confluence = Confluence(
        CONFLUENCE['url'], CONFLUENCE['username'], CONFLUENCE['password'])
    for proj_name, space in PROJECTS.iteritems():
        log.info(u"Creating space {0}".format(space))
        project = redmine.project.get(proj_name)
        confluence.create_space(space, project.name, project.description)
        for wiki_page in project.wiki_pages:
            log.info(u"Importing: {0}".format(wiki_page.title))
            processed = wiki_page.refresh(include='attachments')
```

This is simplier and works without UnicodeDecodeErrors

**Comment by kopf** [comment]
Great! This `.refresh()` really is the solution to all my problems ;)

Thanks for the help!

**Comment by maxtepkeev** [comment]
Haha, yeah. It also helps from different diseases and can save the world sometimes ;-) 

Actually ``refresh()`` is available for all resource objects and you can pass in the same kwargs as to the managers's ``get()`` method, so whenever you're unhappy with the data you received, you can always refresh and receive all available attributes for an object.

**Pull request closed without merging**
